apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: greeting-api
                port:
                  number: 80
