server:
  port: 8082

spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: loan-service
  http:
    serviceclient:
      books:
        base-url: http://localhost:8081
        connect-timeout: 1s
        read-timeout: 2s

resilience4j:
  retry:
    instances:
      books:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    instances:
      books:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 4
        minimum-number-of-calls: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false
  logging:
    export:
      otlp:
        enabled: false
