package com.howtodoinjava.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.Date;

@Data
@DynamoDBTable(tableName = "tbl_movie_dtl")
public class MovieDetail {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute(attributeName = "title")
  private String title;

  @DynamoDBAttribute(attributeName = "year_released")
  private Date year;

  @DynamoDBAttribute(attributeName = "genre")
  private String genre;

  @DynamoDBAttribute(attributeName = "country")
  private String country;

  @DynamoDBAttribute(attributeName = "duration")
  private Integer duration;

  @DynamoDBAttribute(attributeName = "language")
  private String language;
}
