# Used only by BatchJobByQuartzApplication (profile "quartz")
spring.autoconfigure.exclude=
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never

spring.quartz.job-store-type=jdbc
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=false
spring.quartz.properties.org.quartz.scheduler.instanceName=MyScheduler
spring.quartz.properties.org.quartz.threadPool.threadCount=5
