services:
  book-service:
    build: ./book-service
    environment:
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://jaeger:4318/v1/traces

  loan-service:
    build: ./loan-service
    environment:
      SPRING_HTTP_SERVICECLIENT_BOOKS_BASEURL: http://book-service:8081
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://jaeger:4318/v1/traces

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      LIBRARY_BOOKSERVICE: http://book-service:8081
      LIBRARY_LOANSERVICE: http://loan-service:8082
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://jaeger:4318/v1/traces

  jaeger:
    image: jaegertracing/jaeger:2.21.0
    ports:
      - "16686:16686"
