package com.howtodoinjava.demo.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;

public record Recipe(
    @Schema(description = "Generated by the server", accessMode = Schema.AccessMode.READ_ONLY)
    Long id,
    @NotBlank @Schema(example = "Pancakes") String name,
    @Min(1) @Schema(example = "20") int prepMinutes) {
}
