spring.datasource.url=jdbc:h2:mem:authdb
spring.sql.init.schema-locations=\
  classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql,\
  classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql
